### ISSUE TITLE
sequence retry wait doesn't exist

### ISSUE THREAD

**Issue by felixplajer** [square/spincycle#111]
In the docs, there's a retryWait option given for sequences - this doesn't actually exist. We should remove it from the docs (though it's a good idea for a future feature).

**Comment by smanurung** [comment]
I think it does exist (https://github.com/square/spincycle/blob/master/job-runner/runner/runner.go#L72).

**Comment by felixplajer** [comment]
That retry wait is for an individual job, not a whole sequence. A Runner acts on an individual job — sequence retry waits would have to be implemented higher up, in the Traverser or Reaper.
